name: GPG signature
on: [push]
jobs:
  build:
    name: GPG signature
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: GPG signature
        run: |
          sudo apt-get install -y gawk libgmp-dev dirmngr gnupg2
          curl -sSL https://rvm.io/mpapis.asc | gpg --import -
          curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
          gpg2 --verify binscripts/rvm-installer.asc binscripts/rvm-installer
